/**
 * Product-level configuration. Renaming the product or changing the default
 * model should only ever require edits in this file.
 */
export const product = {
  name: "Forma",
  tagline: "Turn an idea into a plan.",
  description:
    "Forma turns what you want to accomplish into a structured, schedulable plan.",
} as const;

/**
 * Plans are generated by an open model running entirely in the visitor's
 * browser (WebGPU via WebLLM). Nothing is sent to an AI provider.
 * Any WebLLM prebuilt model id works; override with NEXT_PUBLIC_LOCAL_MODEL.
 */
const DEFAULT_LOCAL_MODEL = "Qwen3-8B-q4f16_1-MLC";
const localModelId = process.env.NEXT_PUBLIC_LOCAL_MODEL || DEFAULT_LOCAL_MODEL;

export const LOCAL_MODEL = {
  id: localModelId,
  /** "Qwen3-8B-q4f16_1-MLC" → "Qwen3 8B" */
  label: localModelId.replace(/-q\d.*$/, "").replace(/-/g, " "),
  /** Approximate one-time download, shown before the visitor commits to it. */
  downloadLabel: localModelId === DEFAULT_LOCAL_MODEL ? "about 5 GB" : "a one-time download",
  /** Room for the planning prompt plus a complete plan. */
  contextWindow: 8192,
} as const;

export const PLANNING_STYLES = [
  { id: "balanced", label: "Balanced", description: "Realistic pace with room to breathe" },
  { id: "ambitious", label: "Ambitious", description: "Tighter timelines, more output" },
  { id: "gentle", label: "Gentle", description: "Lighter workload, more buffer" },
] as const;
export type PlanningStyle = (typeof PLANNING_STYLES)[number]["id"];

export const RESPONSE_STYLES = [
  { id: "concise", label: "Concise" },
  { id: "detailed", label: "Detailed" },
] as const;
export type ResponseStyle = (typeof RESPONSE_STYLES)[number]["id"];
